name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          CODE_LANG: rust
          BLOCKS: ->
          LANG_COUNT: 10
          TIME_RANGE: last_30_days
          SHOW_TIME: true
          SHOW_TOTAL: true
          STOP_AT_OTHER: true
